name: Build TubeCord
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    strategy:
      matrix:
        java: [8]
        os: ["ubuntu-latest"]
      fail-fast: true

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Configure git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "no-reply@github.com"

      - name: Update upstream
        run: |
          git submodule update --recursive --init

      - name: Apply patches
        run: |
          ./scripts/applyPatches.sh

      - name: Build with Maven
        run: | 
          mvn -B clean package "-Dbuild.number=$GITHUB_RUN_NUMBER"

      - name: Get commit SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TubeCord-${{ env.SHORT_SHA }}
          path: |
            Waterfall-Proxy/bootstrap/target/TubeCord.jar
            Waterfall-Proxy/module/cmd-alert/target/cmd_alert.jar
            Waterfall-Proxy/module/cmd-find/target/cmd_find.jar
            Waterfall-Proxy/module/cmd-kick/target/cmd_kick.jar
            Waterfall-Proxy/module/cmd-list/target/cmd_list.jar
            Waterfall-Proxy/module/cmd-send/target/cmd_send.jar
            Waterfall-Proxy/module/cmd-server/target/cmd_server.jar
            Waterfall-Proxy/module/reconnect-yaml/target/reconnect_yaml.jar

      - name: Upload GitHub Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Waterfall-Proxy/bootstrap/target/TubeCord.jar
            Waterfall-Proxy/module/cmd-alert/target/cmd_alert.jar
            Waterfall-Proxy/module/cmd-find/target/cmd_find.jar
            Waterfall-Proxy/module/cmd-kick/target/cmd_kick.jar
            Waterfall-Proxy/module/cmd-list/target/cmd_list.jar
            Waterfall-Proxy/module/cmd-send/target/cmd_send.jar
            Waterfall-Proxy/module/cmd-server/target/cmd_server.jar
            Waterfall-Proxy/module/reconnect-yaml/target/reconnect_yaml.jar
          name: "TubeCord-${{ env.SHORT_SHA }}-build${{ github.run_number }}"
          tag_name: R1.0-${{ env.SHORT_SHA }}
          target_commitish:  ${{ github.event.ref }}
          generate_release_notes: true
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
